### ISSUE TITLE
MySQL DB Connection Timeout

### ISSUE THREAD

**Issue by dwaring87** [dwaring87/right-track-api-server#6]
API Requests to the MySQL Database timeout if there hasn't been a recent request.  This occurs on both the ARCH and CANY instances of the server.  It appears the idle connections are dropped and the API request is completed before the reconnect happens.  Subsequent requests are fine until the connection is dropped again.

The API Server should detect a lost connection and reconnect before fulfilling the request so an error does not occur.

Error Output:
```
Feb 16 15:57:32 cany start-rt-api: #033[mcom.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was16584 seconds ago.The last packet sent successfull
y to the server was 16584 seconds ago, which  is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your applica
tion, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
Feb 16 15:57:32 cany start-rt-api: at sun.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
Feb 16 15:57:32 cany start-rt-api: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Feb 16 15:57:32 cany start-rt-api: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Feb 16 15:57:32 cany start-rt-api: at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
Feb 16 15:57:32 cany start-rt-api: at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
Feb 16 15:57:32 cany start-rt-api: at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3246)
Feb 16 15:57:32 cany start-rt-api: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1917)
Feb 16 15:57:32 cany start-rt-api: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
Feb 16 15:57:32 cany start-rt-api: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2536)
Feb 16 15:57:32 cany start-rt-api: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
Feb 16 15:57:32 cany start-rt-api: at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1383)
Feb 16 15:57:32 cany start-rt-api: at com.righttrack.core.db.RightTrackDB.select(RightTrackDB.java:238)
Feb 16 15:57:32 cany start-rt-api: at com.righttrack.api.db.query.ApiKeysTable.apiKeyHasAccess(ApiKeysTable.java:47)
Feb 16 15:57:32 cany start-rt-api: at com.righttrack.api.helpers.AuthorizationHelper.validateRequest(AuthorizationHelper.java:112)
Feb 16 15:57:32 cany start-rt-api: at com.righttrack.api.endpoints.GTFS.getStops(GTFS.java:145)
Feb 16 15:57:32 cany start-rt-api: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Feb 16 15:57:32 cany start-rt-api: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Feb 16 15:57:32 cany start-rt-api: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Feb 16 15:57:32 cany start-rt-api: at java.lang.reflect.Method.invoke(Method.java:498)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:377)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
Feb 16 15:57:32 cany start-rt-api: at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.server.Server.handle(Server.java:497)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
Feb 16 15:57:32 cany start-rt-api: at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
Feb 16 15:57:32 cany start-rt-api: at java.lang.Thread.run(Thread.java:745)
Feb 16 15:57:32 cany start-rt-api: Caused by: java.net.SocketException: Broken pipe (Write failed)
Feb 16 15:57:32 cany start-rt-api: at java.net.SocketOutputStream.socketWrite0(Native Method)
Feb 16 15:57:32 cany start-rt-api: at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
Feb 16 15:57:32 cany start-rt-api: at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
Feb 16 15:57:32 cany start-rt-api: at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
Feb 16 15:57:32 cany start-rt-api: at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
Feb 16 15:57:32 cany start-rt-api: at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3227)
Feb 16 15:57:32 cany start-rt-api: ... 51 more
Feb 16 15:57:32 cany start-rt-api: #033[33m[WARN ] 2017-02-16 15:57:32.372 | api.helpers.AuthorizationHelper.validateRequest():113 | API Key: f2062d4bbb247d8c01fbe9e6ddb8da527dabf664a9845aff33307d044a94d76
8 does not have access to scope: gtfs
```

**Comment by dwaring87** [comment]
This is temporarily somewhat fixed by increasing `wait_timeout` in `my.cnf` but should be handled more gracefully by the API Server

**Comment by dwaring87** [comment]
Fixed in right-track-core
